2025-07-30 15:18:08 DEBUG:busco.run_BUSCO	Command line: /storage/mi/voa99/Learn/FUB_SequenceAnalysis_25SoSe/exam/.snakemake/conda/352e770555582bad55b5c7238c3ce868_/bin/busco -i results/assembly/sample5/assembly.fasta -o sample5 -l bacteria_odb10 -m genome --out_path results/qc/busco/sample5 --cpu 16
2025-07-30 15:18:08 INFO:busco.run_BUSCO	***** Start a BUSCO v5.7.1 analysis, current time: 07/30/2025 15:18:08 *****
2025-07-30 15:18:08 DEBUG:busco.ConfigManager	Getting config file
2025-07-30 15:18:08 INFO:busco.ConfigManager	Configuring BUSCO with local environment
2025-07-30 15:18:08 INFO:busco.BuscoConfig	Running genome mode
2025-07-30 15:18:08 ERROR:busco.BuscoRunner	A run with the name /storage/mi/voa99/Learn/FUB_SequenceAnalysis_25SoSe/exam/results/qc/busco/sample5/sample5 already exists...
	If you are sure you wish to overwrite existing files, please use the -f (force) option
2025-07-30 15:18:08 DEBUG:busco.BuscoRunner	A run with the name /storage/mi/voa99/Learn/FUB_SequenceAnalysis_25SoSe/exam/results/qc/busco/sample5/sample5 already exists...
	If you are sure you wish to overwrite existing files, please use the -f (force) option
Traceback (most recent call last):
  File "/storage/mi/voa99/Learn/FUB_SequenceAnalysis_25SoSe/exam/.snakemake/conda/352e770555582bad55b5c7238c3ce868_/lib/python3.10/site-packages/busco/run_BUSCO.py", line 68, in run
    self.load_config()
  File "/storage/mi/voa99/Learn/FUB_SequenceAnalysis_25SoSe/exam/.snakemake/conda/352e770555582bad55b5c7238c3ce868_/lib/python3.10/site-packages/busco/run_BUSCO.py", line 60, in load_config
    self.config_manager.load_busco_config_main()
  File "/storage/mi/voa99/Learn/FUB_SequenceAnalysis_25SoSe/exam/.snakemake/conda/352e770555582bad55b5c7238c3ce868_/lib/python3.10/site-packages/busco/BuscoLogger.py", line 62, in wrapped_func
    self.retval = func(*args, **kwargs)
  File "/storage/mi/voa99/Learn/FUB_SequenceAnalysis_25SoSe/exam/.snakemake/conda/352e770555582bad55b5c7238c3ce868_/lib/python3.10/site-packages/busco/ConfigManager.py", line 63, in load_busco_config_main
    self.config_main.validate()
  File "/storage/mi/voa99/Learn/FUB_SequenceAnalysis_25SoSe/exam/.snakemake/conda/352e770555582bad55b5c7238c3ce868_/lib/python3.10/site-packages/busco/BuscoConfig.py", line 634, in validate
    self._check_no_previous_run()
  File "/storage/mi/voa99/Learn/FUB_SequenceAnalysis_25SoSe/exam/.snakemake/conda/352e770555582bad55b5c7238c3ce868_/lib/python3.10/site-packages/busco/BuscoConfig.py", line 846, in _check_no_previous_run
    raise BatchFatalError(
busco.Exceptions.BatchFatalError: A run with the name /storage/mi/voa99/Learn/FUB_SequenceAnalysis_25SoSe/exam/results/qc/busco/sample5/sample5 already exists...
	If you are sure you wish to overwrite existing files, please use the -f (force) option
2025-07-30 15:18:08 ERROR:busco.BuscoRunner	BUSCO analysis failed!
2025-07-30 15:18:08 ERROR:busco.BuscoRunner	Check the logs, read the user guide (https://busco.ezlab.org/busco_userguide.html), and check the BUSCO issue board on https://gitlab.com/ezlab/busco/issues

